# Generated by Django 4.0 on 2024-11-22 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='user_end_time',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user_start_time',
        ),
        migrations.CreateModel(
            name='UserWorkTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_start_time', models.DateTimeField(blank=True, help_text='User Start Work', null=True, verbose_name='User Tracking')),
                ('user_end_time', models.DateTimeField(blank=True, help_text='User End Work', null=True, verbose_name='User Tracking')),
                ('user', models.ForeignKey(help_text='User', on_delete=django.db.models.deletion.CASCADE, related_name='work_time', to='auth.user', verbose_name='User')),
            ],
        ),
    ]
