# Generated by Django 4.0 on 2024-11-23 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_userinfo_user_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userworktime',
            name='late',
            field=models.BooleanField(default=False, help_text='Late', verbose_name='Late'),
        ),
    ]
