# Generated by Django 4.0 on 2024-11-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_userworktime_options_offrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userworktime',
            name='work_day',
            field=models.DateField(blank=True, help_text='Work Day', null=True, verbose_name='Work Day'),
        ),
        migrations.AlterField(
            model_name='userworktime',
            name='user_end_time',
            field=models.TimeField(blank=True, help_text='User End Work', null=True, verbose_name='User Tracking'),
        ),
        migrations.AlterField(
            model_name='userworktime',
            name='user_start_time',
            field=models.TimeField(blank=True, help_text='User Start Work', null=True, verbose_name='User Tracking'),
        ),
    ]
