# Generated by Django 4.0 on 2024-11-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_userworktime_work_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userworktime',
            name='user_end_time',
            field=models.TimeField(blank=True, help_text='User End Work', null=True, verbose_name='User End Work'),
        ),
        migrations.AlterField(
            model_name='userworktime',
            name='user_start_time',
            field=models.TimeField(blank=True, help_text='User Start Work', null=True, verbose_name='User Start Work'),
        ),
    ]
