# Generated by Django 4.0 on 2024-11-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_userworktime_user_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='status',
        ),
        migrations.AddField(
            model_name='userworktime',
            name='status',
            field=models.BooleanField(default=False, help_text='User Work Status'),
        ),
    ]
