# Generated by Django 4.0 on 2024-11-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_userinfo_status_userworktime_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offrequest',
            name='status',
            field=models.CharField(choices=[('Onaylandı', 'Onaylandı'), ('Reddedildi', 'Reddedildi'), ('Beklemede', 'Beklemede')], default='Beklemede', help_text='Status', max_length=50, verbose_name='Status'),
        ),
    ]
