# Generated by Django 4.0 on 2024-11-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_key',
            field=models.CharField(help_text='Type', max_length=50, verbose_name='Type'),
        ),
    ]
